package com.elliott.supervideoplayer.model;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table VIDEO_BEAN.
 */
public class VideoBean {
    private Long id;
    /** Not-null value. */
    private String VideoName;
    private String VideoLink;
    private String thumbnailPath;
    private String totalsize;
    private String totalduration;
    private Integer type;

    public VideoBean() {
    }

    public VideoBean(Long id) {
        this.id = id;
    }

    public VideoBean(Long id, String VideoName, String VideoLink, String thumbnailPath, String totalsize, String totalduration, Integer type) {
        this.id = id;
        this.VideoName = VideoName;
        this.VideoLink = VideoLink;
        this.thumbnailPath = thumbnailPath;
        this.totalsize = totalsize;
        this.totalduration = totalduration;
        this.type = type;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getVideoName() {
        return VideoName;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setVideoName(String VideoName) {
        this.VideoName = VideoName;
    }

    public String getVideoLink() {
        return VideoLink;
    }

    public void setVideoLink(String VideoLink) {
        this.VideoLink = VideoLink;
    }

    public String getThumbnailPath() {
        return thumbnailPath;
    }

    public void setThumbnailPath(String thumbnailPath) {
        this.thumbnailPath = thumbnailPath;
    }

    public String getTotalsize() {
        return totalsize;
    }

    public void setTotalsize(String totalsize) {
        this.totalsize = totalsize;
    }

    public String getTotalduration() {
        return totalduration;
    }

    public void setTotalduration(String totalduration) {
        this.totalduration = totalduration;
    }

    public Integer getType() {
        return type;
    }

    public void setType(Integer type) {
        this.type = type;
    }

}
