package com.elliott.supervideoplayer.db;

import android.database.sqlite.SQLiteDatabase;

import com.elliott.supervideoplayer.model.VideoBean;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig videoBeanDaoConfig;

    private final VideoBeanDao videoBeanDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        videoBeanDaoConfig = daoConfigMap.get(VideoBeanDao.class).clone();
        videoBeanDaoConfig.initIdentityScope(type);

        videoBeanDao = new VideoBeanDao(videoBeanDaoConfig, this);

        registerDao(VideoBean.class, videoBeanDao);
    }
    
    public void clear() {
        videoBeanDaoConfig.getIdentityScope().clear();
    }

    public VideoBeanDao getVideoBeanDao() {
        return videoBeanDao;
    }

}
